project:
  type: book
  output-dir: docs
  
  preview: 
    port: 33333
    browser: true
    watch-inputs: true
    navigate: true

book:
  title: "R Code for 'A Practical Guide . . .'"
  author: "John Maindonald"
  date: "2024-06-02"
  repo-url: https://github.com/jhmaindonald/code/
  downloads: [pdf, docx]

  chapters:
    - index.qmd
    - ch1.qmd
    - ch2.qmd
    - ch3.qmd
    - ch4.qmd
    - ch5.qmd
    # - ch6.qmd
    # - ch7.qmd
    # - ch8.qmd
    - ch9.qmd
    - Appendix.qmd
  
  navbar:
    pinned: true
    title: false
    logo: /cover.png
    logo-href: https://ten-z.github.io/PGRTestLandingpage/
    
    # your sub-pages
    left:
      - text: "About"
        href: https://ten-z.github.io/PGRTestLandingpage/
      - text: "Blog"
        href: https://ten-z.github.io/PGRTestLandingpage/blog.html
      - text: "Book"
        href: index.qmd
        
  search: 
    location: navbar
    type: textbox
  page-footer:
    left: "&copy; Copyright 2022, Author"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

bibliography: references.bib

format:
  html:
    number-depth: 1
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
  pdf:
    number-depth: 1
    documentclass: scrreprt
    toc: true
  docx: 
    number-depth: 1
    toc: true
    
    



