project:
  type: book
  output-dir: docs
  
  preview: 
    port: 33333
    browser: true
    watch-inputs: true
    navigate: true

book:
  title: "R Code for 'A Practical Guide . . .'"
  author: "John Maindonald"
  date: "2024-06-02"
  repo-url: https://github.com/jhmaindonald/code/
  downloads: [pdf, docx]
  
  comments:
    hypothesis: true

  chapters:
    - index.qmd
    - ch1.qmd
    - ch2.qmd
    - ch3.qmd
    - ch4.qmd
    - ch5.qmd
    # - ch6.qmd
    # - ch7.qmd
    # - ch8.qmd
    - ch9.qmd
    - Appendix.qmd
  
  navbar:
    pinned: true
    title: false
    left:
      - text: "Home"
        href: https://ten-z.github.io/SupplementsTest/
      - text: "Practical Guide"
        href: https://ten-z.github.io/SupplementsTest/about.html
      - text: "Blog"
        href: https://ten-z.github.io/SupplementsTest/blog.html
      - text: "R code"
        href: index.qmd
        
    right: 
      - text: "Resources"
        menu:
          - text: "Afterword"
            href: https://ten-z.github.io/SupplementsTest/afterword.html
          - text: "Ways to Use Code"
            href: https://ten-z.github.io/SupplementsTest/RunningCode.html
          - text: "Code for Selected Figures"
            href: https://ten-z.github.io/SupplementsTest/figFuns.html

bibliography: references.bib

format:
  html:
    number-depth: 1
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
  pdf:
    number-depth: 1
    documentclass: scrreprt
    toc: true
  docx: 
    number-depth: 1
    toc: true
    
    



